const LIGHT_THEME = {
	name: 'Light',
	FONT: {
		MAIN: 'inter-semi',
		SECONDARY: 'space'
	},
	SLIDER: {
		ARC_COLOUR: '0x000000',
		INDICATOR_COLOUR: '0x6b6b6b',
		UPPER_GRADIENT_COLOUR: '0xF6F6F6',
		LOWER_GRADIENT_COLOUR: '0xEAEAEA',
		BORDER_COLOUR: '0xDFDFDF',
		SHADOW_COLOUR: '0x3e3234',
		RED_COLOUR: '0xFF0000',
		BLUE_COLOUR: '0x0023FF',
	},
	PANEL: {
		UPPER_GRADIENT_COLOUR: '0xDDDDDD',
		LOWER_GRADIENT_COLOUR: '0xE6E6E6',
		MAIN_UPPER_GRADIENT_COLOUR: '0xECECEC',
		MAIN_LOWER_GRADIENT_COLOUR: '0xD3D3D3',
		BORDER_COLOUR: '0xA5A5A5',
		SELECTED_ICON_COLOUR: '0x6B6B6B',
		ICON_COLOUR: '0xA3A3A3',
		HOVER_OPACITY: 'CC',
		TEXT_COLOUR: 4285229931
	},					
	BUTTON: {
		PHYSICAL: {
			UPPER_GRADIENT_COLOUR: '0xF6F6F6',
			LOWER_GRADIENT_COLOUR: '0xEAEAEA',
			BACKGROUND_HOVER_COLOUR: '0xF5F5F5',
			BORDER_COLOUR: '0xA5A5A5',
			SHADOW_COLOUR: '0x3e3234',
			ICON_COLOUR: '0x6b6b6b',
		}
	},
	DISPLAY: {
		BUTTON_BACKGROUND_COLOUR: '0x000000',
		BUTTON_SELECTED_BACKGROUND_COLOUR: '0xffffff',
		BUTTON_TEXT_COLOUR: '0xffffff',
		BUTTON_SELECTED_TEXT_COLOUR: '0x000000',
		TEXT_COLOUR: '0xffffff',
		HOVER_OPACITY: 'CC',
		SELECTED_ICON_COLOUR: '0xffffff',
		ICON_COLOUR: '0xAAAAAA',
		NOT_ACTIVATED_COLOUR: '0xFF0000',
	},
	HEADER: {
		SELECTED_ICON_COLOUR: '0xA3A3A3',
		ICON_COLOUR: '0x6B6B6B',
		SELECTED_TEXT_COLOUR: '0xA3A3A3',
		TEXT_COLOUR: '0x6B6B6B',
		HOVER_OPACITY: 'CC'
	}
};

const DARK_THEME = {
	name: 'Dark',
	FONT: {
		MAIN: 'inter-semi',
		SECONDARY: 'space'
	},
	SLIDER: {
		ARC_COLOUR: '0x969696',
		INDICATOR_COLOUR: '0x969696',
		UPPER_GRADIENT_COLOUR: '0x2D2D2D',
		LOWER_GRADIENT_COLOUR: '0x181818',
		BORDER_COLOUR: '0x333333',
		SHADOW_COLOUR: '0x3e3234',
		RED_COLOUR: '0xFBFF0000',
		BLUE_COLOUR: '0xFB0023FF',
	},
	PANEL: {
		UPPER_GRADIENT_COLOUR: '0x262626',
		LOWER_GRADIENT_COLOUR: '0x232323',
		MAIN_UPPER_GRADIENT_COLOUR: '0x323232',
		MAIN_LOWER_GRADIENT_COLOUR: '0x282828',
		BORDER_COLOUR: '0x2D2D2D',
		SELECTED_ICON_COLOUR: '0xE3E3E3',
		ICON_COLOUR: '0x696A69',
		HOVER_OPACITY: 'CC',
		TEXT_COLOUR: 4293125091
	},
	BUTTON: {
		PHYSICAL: {
			UPPER_GRADIENT_COLOUR: '0x2D2D2D',
			LOWER_GRADIENT_COLOUR: '0x181818',
			BACKGROUND_HOVER_COLOUR: '0x282828',
			BORDER_COLOUR: '0x333333',
			SHADOW_COLOUR: '0x3e3234',
			ICON_COLOUR: '0x969696',
		}
	},
	DISPLAY: {
		BUTTON_BACKGROUND_COLOUR: '0x000000',
		BUTTON_SELECTED_BACKGROUND_COLOUR: '0xffffff',
		BUTTON_TEXT_COLOUR: '0xffffff',
		BUTTON_SELECTED_TEXT_COLOUR: '0x000000',
		TEXT_COLOUR: '0xffffff',
		HOVER_OPACITY: 'CC',
		SELECTED_ICON_COLOUR: '0xffffff',
		ICON_COLOUR: '0xAAAAAA',
		NOT_ACTIVATED_COLOUR: '0xFF0000',
	},
	HEADER: {
		SELECTED_ICON_COLOUR: '0xA3A3A3',
		ICON_COLOUR: '0xE3E3E3',
		SELECTED_TEXT_COLOUR: '0xA3A3A3',
		TEXT_COLOUR: '0xE3E3E3',
		HOVER_OPACITY: 'CC',
	}
};

var THEME = LIGHT_THEME;

function setTheme(theme) {
	if(theme == 'Light') {
		THEME = LIGHT_THEME;
		STATE.theme = 'Light';
	}
	if (theme == 'Dark') {
		THEME = DARK_THEME;
		STATE.theme = 'Dark';
	}
	
	repaintAllPanels();
	themeLabels();
	
	saveSettings();
}