/** Autogenerated Main.cpp. */

#include <JuceHeader.h>
#include "includes.h"

// ======================================| Project Factory |======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations -------------------------------------------------------------------
		
		registerPolyNode<project::FaustReverb<1>, project::FaustReverb<NUM_POLYPHONIC_VOICES>>();
		registerNode<project::Flair>();
		registerPolyNode<project::Reverb<1>, wrap::illegal_poly<project::Reverb<1>>>();
		registerDataNode<project::Degrade_networkdata>();
		registerDataNode<project::NoiseGen_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* hise::FrontendHostFactory::createStaticFactory()
{
	return new project::Factory();
}

