/** Autogenerated Main.cpp. */

#include <JuceHeader.h>
#include "includes.h"

// ======================================| Project Factory |======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations -------------------------------------------------------------------
		
		registerPolyNode<project::Flanger<1>, project::Flanger<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::FaustReverb<1>, project::FaustReverb<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Distortion<1>, project::Distortion<NUM_POLYPHONIC_VOICES>>();
		registerNode<project::Chorus2>();
		registerPolyNode<project::Degrade<1>, wrap::illegal_poly<project::Degrade<1>>>();
		registerPolyNode<project::Flair<1>, wrap::illegal_poly<project::Flair<1>>>();
		registerPolyNode<project::Reverb<1>, wrap::illegal_poly<project::Reverb<1>>>();
		registerPolyNode<project::Waveshaper<1>, wrap::illegal_poly<project::Waveshaper<1>>>();
		registerDataNode<project::ReverbParameters_networkdata>();
		registerDataNode<project::test_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* hise::FrontendHostFactory::createStaticFactory()
{
	return new project::Factory();
}

