/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "Distortion.h"
#include "FaustReverb.h"
#include "Flanger.h"

// Include compiled network files ------------------

#include "Chorus2.h"
#include "Degrade.h"
#include "Flair.h"
#include "Reverb.h"
#include "ReverbParameters_networkdata.h"
#include "test_networkdata.h"
#include "Waveshaper.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

